In [ ]:
#Frequency

    subject Codingcasino 50 points

Description
Write a Python program that does the following:

    takes a list as input
    creates a Pandas Series from the list
    prints the frequency count of each unique value in the Series


Input Format

    The first line contains space-separated values, which represent the elements of a list


Output Format

    Print the frequency count of each unique value (in ascending order), with its dtype, to STDOUT


Sample Test Cases

Sample Input #1

a a a b c c c d d d d e e e e e f f f f f f g g g g g g g h h h h h h h h

Sample Output #1

a    3
b    1
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64

In [2]:
import pandas as pd
import numpy as np

In [2]:
n=[]
n=input().split(' ')
series = pd.Series(n)
result=series.value_counts()
print(result.sort_index())

a a a b c c c d d d d e e e e e f f f f f f g g g g g g g h h h h h h h h
a    3
b    1
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64

In [ ]:
Alphabets

    subject Codingcasino 50 points

Description
You have been given a list of English alphabets. Create a Pandas Series from it and assign this Series a Name, which can be obtained from the input.

Input Format

    The first line of STDIN contains a string that represents the Name for the Series.


Output Format

    Based on the input, print the Series with its Name and dtype.


Sample Test Cases

Sample Input

alphabets


Sample Output

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: alphabets, dtype: object

In [3]:
inp=input()
ls =list('abcedfghijklmnopqrstuvwxyz')
ls= pd.Series(ls, name=inp, dtype=object)
print(ls)

alphabets
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: alphabets, dtype: object

In [ ]:
Not Present

    subject Codingcasino 50 points

Description
You have to write a program that does the following:

    takes two lists as inputs
    creates two Pandas Series from the above lists - series1 and series2
    removes all items from series1 which are present in series2


Input Format

    The first line contains elements of the first list - list1
    The second line contains elements of the second list - list2


Output Format

    Print all elements of the Series and its dtype, after performing the required operations as given in the Problem Statement.


Sample Test Cases

Sample Input

4 5 2 3 4 1
4 5 6 7 8


Sample Output

2    2
3    3
5    1
dtype: object

In [4]:
s=input()
se=pd.Series([i for i in s.split()])
s1=input()
se1= pd.Series([i for i in s1.split()])
ls=se[~se.isin(se1)]
print(ls)

4 5 2 3 4 1
4 5 6 7 8
2    2
3    3
5    1
dtype: object

In [ ]:
Marines! At Your Positions!!

    subject Codingcasino 50 points

Description
Write a Python program that does the following:

    takes a list as input - list_input
    takes another list as input - list_pos
    creates a Pandas Series from list_input
    prints all values of list_input which are present at the positions listed out by list_pos


Input Format

    The first line contains space-separated values (this value can be of any data type), which represent the elements of the list list_input
    The second line contains space-separated integers, which represent the elements of the list list_pos.
        These positions are on 0-based indexing, i.e. indexing starts from 0.


Output Format

    For the positions listed out by list_pos, print all values from list_input which are present at those locations, along with its dtype


Sample Test Cases

Sample Input

a b c d e f g h i j k l m n o p q r s t u v w x y z
0 4 8 14 20


Sample Output

0     a
4     e
8     i
14    o
20    u
dtype: object

In [1]:
import pandas as pd
ls=input()
ls=[k for k in ls.split()]
ls1=[int(k) for k in input().split()]
ls2=[]
for i in ls1:
    a=ls[i]
    ls2.append(a)
se=pd.Series(index=ls1,data=ls2)
print(se)

a b c d e f g h i j k l m n o p q r s t u v w x y z
0 4 8 14 20
0     a
4     e
8     i
14    o
20    u
dtype: object

In [ ]:
NumPy Array

    subject Codingcasino 50 points

Description
Write a simple program that takes three integers as input: stp, enp and step ; and uses these values to return evenly spaced values within the given interval.

Input Format

    The first line contains an integer - stp which represents the start of the interval.
    The second line contains an integer - enp which represents the end of the interval.
    The third line contains an integer - step which represents the spacing between consecutive values.

Constraints

    1 <= stp < enp <= 105
    2 <= step < enp <= 105


Output Format

    If the above constraints are not satisfied, print "Constraints are failing!"
    If the above constraints are satisfied, print each element of the list in a new line, as is generated using the condition described in the Problem Statement.


Sample Test Cases

Sample Input #1

2
11
3


Sample Output #1

2
5
8
11

In [15]:
stp = int(input())
enp = int(input())
step = int(input())
ls= np.arange(stp,enp+1,step)
if enp<=100000 and stp<enp and stp>=1 and step<enp and step>=2:
    for i in ls:
        print(i)
else:
    
    print("Constraints are failing!")

2
11
3
2
5
8
11

In [ ]:
Stacked against Each Other

    subject Codingcasino 50 points

Description
Write a Python program that does the following:

    takes two lists as input - list1 and list2
    creates two Pandas Series out of them
    stacks / concatenates both Series vertically and horizontally, along the column axis (axis = 1)


Input Format

    The first line contains space-separated values, which represent the elements of the first list list1
    The second line contains space-separated values, which represent the elements of the second list list2


Constraints

    length of list1 = length of list2


Output Format

    Print the dataframe containing the required output, with list1 being the first column and list2 being the second column 
    If the above constraint is NOT satisfied, print NaN for all missing values


Sample Test Cases

Sample Input #1

0 1 2 3 4
a b c d e


Sample Output #1

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


Explanation #1

    Both lists are converted into Series and then stacked against each other.
    Then, the stacked/concatenated DataFrame is printed to STDOUT.



Sample Input #2

0 1 2 3
a b c d e


Sample Output #2

     0  1
0    0  a
1    1  b
2    2  c
3    3  d
4  NaN  e

In [ ]:
ls=[ i for i in input().split(" ")]
ls1=[ k for k in input().split(" ")]
st=pd.Series(ls)
st1=pd.Series(ls1)
series=pd.concat([st,st1], axis=1)
print(series)

In [ ]:
That's Pretty Uncommon!

    subject Codingcasino 50 points

Description
Write a program that does the following:

    takes two lists as inputs
    creates two Pandas Series out of the lists
    prints all those elements which are not common to either of the lists.


Input Format

    The first line contains space-separated values, which represent the elements of the first list list1
    The second line contains space-separated values, which represent the elements of the second list list2


Output Format

    Print all those elements of both lists, which are not common between both; along with their dtype


Sample Test Cases

Sample Input

1 2 3 4 5 6
4 5 6 7 8 9


Sample Output

0    1
1    2
2    3
6    7
7    8
8    9
dtype: object

In [21]:
ls=input().split(" ")
ls1=input().split(" ")
s1= pd.Series(ls)
s2= pd.Series(ls1)
sort1=pd.Series(sorted(list(set(s1).intersection(set(s2)))))
sort1

1 2 3 4 5 6
4 5 6 7 8 9

0    4
1    5
2    6
dtype: object

In [5]:
ls=input().split(" ")
ls1=input().split(" ")
s1= pd.Series(ls)
s2= pd.Series(ls1)
sort1=pd.Series(sorted(list(set(s1).union(set(s2)))))
sort2=pd.Series(sorted(list(set(s1).intersection(set(s2)))))
output= pd.concat([sort1,sort2]).drop_duplicates(keep=False)
output = output.astype('object')
print(output)

1 2 3 4 5 6
4 5 6 7 8 9
0    1
1    2
2    3
6    7
7    8
8    9
dtype: object

In [ ]:
Difference of Difference

    subject Codingcasino 50 points

Description
Write a Python program that does the following:

    takes an integer list as input
    creates a Pandas Series from the list
    prints the difference of the difference between consecutive elements of the list


Input Format

    The first line contains space-separated integers, which represent the elements of the input list


Output Format

    Print the difference of the consecutive elements of the list on the first line.
    Print the difference of the difference of the elements obtained from the above, on the second line
    For missing values, print nan (missing values will be present when you try to subtract the 0th element from the 1st element)


Sample Test Cases

Sample Input

2 4 6 8 10 12 14 16


Sample Output

[nan, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
[nan, nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [16]:
ls=[float(x) for x in input().split()]
ls=pd.Series(ls)
s1=ls.diff()
s2=s1.diff()
print(list(s1))
print(list(s2))

2 4 6 8 10 12 14 16
[nan, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
[nan, nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [ ]:
Conversion

    subject Codingcasino 50 points

Description
You have to write a Python program which does the following:

    takes a list as input
    converts the list into a Pandas Series
    reshapes the Series into a dataframe of the order m x n, i.e. the dataframe has m rows and n columns


Input Format

    The first line contains two space-separated integers, representing the values of m and n respectively.
    The second line contains space-separated integers, which represent the elements of the list


Output Format

    If the product of m and n equals the length of the input list, print the converted dataframe
    If the product of m and n is NOT EQUAL to the length of the input list, print the message "Weird Order!"


Constraints

    2 <= m, n <= 10
    The product of m and n should be equal to the length of the input list


Sample Test Cases

Sample Input #1

2 3
1 2 3 4 5 6 7 8


Sample Output #1

Weird Order!


Explanation #1
Since the product of m and n is NOT EQUAL to the length of the input list, hence print "Weird Order!"


Sample Input #2

2 4
1 2 3 4 5 6 7 8


Sample Output #2

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [19]:
ls1= [int(i) for i in input().split()]
ls2= [int(i) for i in input().split()]
ls1= pd.Series(ls1)
ls2= pd.Series(ls2)
g1 = len(ls1)
l1 = [ls1[i] for i in range(g1) if ls1[i] in ls2.values]
l2= [i for i in range(g1) if ls1[i]in l1]
out=ls1.drop(l2).astype('object')
print(out)

2 4
1 2 3 4 5 6 7 8
Series([], dtype: object)

In [ ]:
Conversion

    subject Codingcasino 50 points

Description
You have to write a Python program which does the following:

    takes a list as input
    converts the list into a Pandas Series
    reshapes the Series into a dataframe of the order m x n, i.e. the dataframe has m rows and n columns


Input Format

    The first line contains two space-separated integers, representing the values of m and n respectively.
    The second line contains space-separated integers, which represent the elements of the list


Output Format

    If the product of m and n equals the length of the input list, print the converted dataframe
    If the product of m and n is NOT EQUAL to the length of the input list, print the message "Weird Order!"


Constraints

    2 <= m, n <= 10
    The product of m and n should be equal to the length of the input list


Sample Test Cases

Sample Input #1

2 3
1 2 3 4 5 6 7 8


Sample Output #1

Weird Order!


Explanation #1
Since the product of m and n is NOT EQUAL to the length of the input list, hence print "Weird Order!"


Sample Input #2

2 4
1 2 3 4 5 6 7 8


Sample Output #2

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [6]:
m,n = input().split()
m = int(m)
n = int (n)
input_list = input().split()
a1=pd.Series(input_list)
if (m*n == len(input_list)) & (m>=2 & n<= 10):
    a2=pd.DataFrame(a1.values.reshape(m , n))
    print(a2)
else:
    print("Weird Order!")

2 4
1 2 3 4 5 6 7 8
   0  1  2  3
0  1  2  3  4
1  5  6  7  8